(define (even? num)
  (= (remainder num 2) 0))
(define (double num)
  (+ num num))
(define (halve num)
  (/ num 2))
(define (mul-iter s a n)
  (cond ((= n 0) s)
        ((even? n) (mul-iter s (double a) (halve n)))
        (else (mul-iter (+ s a) (double a) (halve (- n 1))))))
(define (mul a n)
  (mul-iter 0 a n))
