(define (smallest-divisor n)
  (define (next test-divisor)
    (if (= test-divisor 2)
        3
        (+ 2 test-divisor)))
  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((= (remainder n test-divisor) 0) test-divisor)
          (else (find-divisor n (next test-divisor)))))
  (find-divisor n 2))

(define (prime? n)
  (= (smallest-divisor n) n))

(define (next-odd n)
  (if (even? n)
      (+ n 1)
      (+ n 2)))

(define (continue-primes n count)
  (cond ((= count 0) (display "are primes"))
        ((prime? n)
         (display n)
         (newline)
         (continue-primes (next-odd n) (- count 1)))
        (else (continue-primes (next-odd n) count))))

(define (search-for-primes n)
  (let ((start-time (real-time-clock)))
    (continue-primes n 3)
    (- (real-time-clock) start-time)))
