(define (integral f start end n)
  (define h (/ (- end start) n))
  (define (sum term a next b)
    (if (> a b)
        0
        (+ (term a)
           (sum term (next a) next b))))
  (define (coef k)
    (cond ((or (= k 0) (= k n)) 1)
          ((even? k) 2)
          (else 4)))
  (define (term k)
    (* (coef k)
       (f (+ start (* k h)))))
  (define (next k)
    (+ k 1))
  (* (/ h 3)
     (sum term (exact->inexact 0) next n)))
