(define (make-from-mag-ang r theta)
  (lambda (op)
    (cond ((eq? op 'real-part)
           (* r (cos theta)))
          ((eq? op 'imga-part)
           (* r (sin theta)))
          ((eq? op 'magnitude) r)
          ((eq? op 'angle) theta)
          (else (error "Uknown op: MAKE-FROM-MAG-ANG", op)))))
