(define (make-rand)
  (let ((seed 20190717)
        (a 69069)
        (c 1)
        (m (expt 2 32)))

  (lambda (op)
    (cond ((eq? op 'generate)
           (set! seed (modulo (+ (* seed a) c) m))
           (exact->inexact (/ seed m)))
          ((eq? op 'reset)
           (lambda (new-seed)
             (set! seed new-seed)))
          (else (error "Unknown op MAKE-RAND -- " op))))))
